# Generated by Django 5.1.2 on 2024-10-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
